// Builder
export const CHANGE_PIZZA_INGREDIENT = "CHANGE_INGREDIENT";
export const CHANGE_PIZZA_TYPE = "CHANGE_PIZZA_TYPE";
export const SET_BUILDER_CONFIG = "SET_BUILDER_CONFIG";
export const SET_BUILDER_STATE = "SET_BUILDER_STATE";
export const SET_INITIAL_STATE = "SET_INITIAL_STATE";

// Cart
export const CHANGE_MISC_COUNT = "CHANGE_MISC_COUNT";
export const CHANGE_PIZZA_COUNT = "CHANGE_PIZZA_COUNT";
export const ADD_TO_CART = "ADD_TO_CART";
export const RESET_CART_STATE = "RESET_CART_STATE";
export const FILL_ADDRESS_INPUTS = "FILL_ADDRESS_INPUTS";
export const CLEAR_ADDRESS_INPUTS = "CLEAR_ADDRESS_INPUTS";
export const SET_CART_STATE = "SET_CART_STATE";
export const FILL_CART = "FILL_CART";

// Popups
export const OPEN_POPUP = "OPEN_POPUP";
export const CLOSE_POPUP = "CLOSE_POPUP";
export const REGISTER_POPUP = "REGISTER_POPUP";

// Notifications
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";

// Addresses
export const CHANGE_FORM_MODE = "CHANGE_FORM_MODE";
export const EDIT_ADDRESS = "EDIT_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const NEW_ADDRESS = "NEW_ADDRESS";
export const SET_ADDRESSES_STATE = "SET_ADDRESSES_STATE";

// Orders
export const DELETE_ORDER = "DELETE_ORDER";
export const SET_ORDERS = "SET_ORDERS";

// Auth
export const SET_USER = "SET_USER";

// Common
export const SET_ENTITY = "SET_ENTITY";
