// Builder
export const CHANGE_PIZZA_NAME = "CHANGE_PIZZA_NAME";
export const CHANGE_PIZZA_INGREDIENT = "CHANGE_INGREDIENT";
export const CHANGE_PIZZA_TYPE = "CHANGE_PIZZA_TYPE";
export const RESET_BUILDER_STATE = "RESET_BUILDER_STATE";
export const SET_BUILDER_CONFIG = "SET_BUILDER_CONFIG";

// Cart
export const CHANGE_MISC_COUNT = "CHANGE_MISC_COUNT";
export const CHANGE_PIZZA_COUNT = "CHANGE_PIZZA_COUNT";
export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_FORM = "CHANGE_FORM";
export const CLEAR_ADDRESS_INPUTS = "CLEAR_ADDRESS_INPUTS";
export const FILL_ADDRESS_INPUTS = "FILL_ADDRESS_INPUTS";
export const RESET_CART_STATE = "RESET_CART_STATE";

//Popups
export const OPEN_POPUP = "OPEN_POPUP";
export const CLOSE_POPUP = "CLOSE_POPUP";
export const REGISTER_POPUP = "REGISTER_POPUP";
